- name: install nginx server
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: enable and start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  register: nginx_info
  ignore_errors: yes

- name: print the output
  ansible.builtin.debug:
    msg: Nginx info {{ nginx_info }}

- name: Include common role
  ansible.builtin.include_role:
    name: common
    tasks_from: main

# - name: delete html directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: absent

# - name: create html directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: directory

# - name: download frontend code
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /tmp/frontend.zip

# - name: unzip frontend code
#   ansible.builtin.unarchive:
#     src: /tmp/frontend.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

- name: copy frontend config
  ansible.builtin.template:
    src: frontend.conf.j2
    dest: /etc/nginx/default.d/frontend.conf
  notify:
  - Restart the nginx