- name: Install python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMySQL
    - cryptography
  
  - name: Install mysql server
    ansible.builtin.package:
      name: mysql-server 
      state: present

  - name: Enable and restart mysql service
    ansible.builtin.service:
     name: mysqld
     enabled: yes
     state: restarted

  - name: connect to the mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: 172.31.24.31
    register: mysql_info
    ignore_errors: "true"

  - name: print the output
    ansible.builtin.debug:
      msg: "mysql info {{ mysql_info }}"

  - name: setup root password for sql
    ansible.builtin.command: mysql_secure_installation --set-root-pass {{ mysql_root_password }}
    when: mysql_info.failed is true