- name: delete APP directory
  ansible.builtin.file:
    path: "{{ APPCODE_LOCATION }}"
    state: absent

- name: create APP directory
  ansible.builtin.file:
    path: "{{ APPCODE_LOCATION }}"
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip
    dest: "{{ APPCODE_LOCATION }}"
    remote_src: yes